Update iniciar

diff --git a/iniciar b/iniciar
--- a/iniciar
+++ b/iniciar
@@ -1,7 +1,9 @@
 #!/bin/sh
 # File: Iniciar
 errorEjecutando="Error iniciando servicio"
-errorDown="Error descargando";
+errorDown(){
+echo "Error descargando" && exit;
+}
 _hoy=$(date +"%m_%d_%Y_%r_%S")
 _pwd=$(pwd)
 _permisos=$(ls -la *)
@@ -27,7 +29,7 @@ echo '
 
 iniciar_carga() {
 
-curl -o iniciar https://raw.githubusercontent.com/juanma386/desplegar/master/iniciar && mv iniciar $iniciar && chmod +x $iniciar;||echo $errorDown
+curl -o iniciar https://raw.githubusercontent.com/juanma386/desplegar/master/iniciar && mv iniciar $iniciar && chmod +x $iniciar;||errorDown
 dos2unix iniciar
 chmod +x iniciar
 sudo cp iniciar /usr/bin/iniciar
